In [5]:
import numpy as np

In [8]:
# ndarry(다차원 배열) 
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [9]:
type(a)
# 한가지 자료형만 들어갈 수 있다.
a.dtype.name

'int32'

In [7]:
nums = ['a', 2, 'b', 'c', True, 3.14]
nums

['a', 2, 'b', 'c', True, 3.14]

In [12]:
#자료형이 하나로(문자열) 바뀜
b = np.array(nums)
b

array(['a', '2', 'b', 'c', 'True', '3.14'], dtype='<U32')

In [16]:
a = np.array([1,2,3,4,5])
#원소갯수
a.size
#차원
a.ndim
#헹,열
a.shape

(5,)

In [21]:
a = np.array([
            [1,2,3],
            [4,5,6]
            ])
a.size
a.ndim
a.shape
a.itemsize
a.data

In [24]:
a = np.array((
            [1,2,3],
            (4,5,6)
            ))
a

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
bool_array = np.array([True, False, False])
bool_array

array([ True, False, False])

In [27]:
float_array = np.array([1.2, 3.4, 5.6])
float_array
float_array.dtype.name

'float64'

In [31]:
complex_array = np.array([1+2j, 3+4j, 5+2j], dtype=complex)
complex_array
complex_array.dtype.name

'complex128'

In [32]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# 함수형 프로그래밍 (Functional Programming)
* map(): 컬랙션 원소에 대해 특정 계산을 적용함
* filter(): 컬렉션 원소에 대해 특정 원소만 필터링하여 새 집합 생성
* reduce(): 컬렉션 원소에 대해 계산을 수행하여 한개의 스칼라 값을 생성
* lamda(): 위의 함수에서 사용하는 첫번째 아규먼트인 함수(익명함수)

In [44]:
nums = [1,2,3,4,5]

def add(x): return x+1
list(map(add, nums))

[2, 3, 4, 5, 6]

In [49]:
def odd(x): return x%2==1
list(filter(odd, nums))

[1, 3, 5]

In [46]:
from functools import reduce

def sub(x, y): return x+y
reduce(sub, nums)

15

In [52]:
list(map(lambda x : x+1, nums))

[2, 3, 4, 5, 6]

In [53]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [65]:
import random

dataframe = np.zeros([2,3])

for i in range(2):
      for j in range(3):
            dataframe[i,j] = random.randint(1,9)
dataframe

array([[9., 9., 4.],
       [8., 2., 9.]])

In [3]:
rg = range(5) #range object란
for _ in rg:
      print(_, end=",")

lst = list(rg)
type(lst)

0,1,2,3,4,

list

In [7]:
np.arange(3,6) #ndarry의 원소 범위

array([3, 4, 5])

In [9]:
a = np.arange(3, 10, 2)
a

array([3, 5, 7, 9])

In [10]:
np.arange(1, 10, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [14]:
a = np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [15]:
a.shape

(12,)

In [16]:
b=a.reshape(3,4)

In [17]:
b.shape

(3, 4)

In [18]:
a.reshape(2, -1)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [19]:
np.linspace(0, 10, 7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

In [20]:
np.linspace(0, 10, 5, endpoint=True)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [22]:
a = np.random.random(16).reshape((4,4))
a

array([[0.24387188, 0.07604587, 0.69673442, 0.20400895],
       [0.49078358, 0.57079051, 0.38149143, 0.35612561],
       [0.72173139, 0.65417448, 0.53884645, 0.17162582],
       [0.55985262, 0.54790809, 0.24236224, 0.71630387]])

In [26]:
a = np.random.random(16).reshape((2,-1))
a

array([[0.98113162, 0.25215713, 0.95611457, 0.15409948, 0.40051184,
        0.32808972, 0.39998962, 0.83927836],
       [0.7268405 , 0.06647424, 0.13775801, 0.09340984, 0.31842996,
        0.66482999, 0.03565542, 0.67810608]])

In [27]:
a.data

In [28]:
a1 = a.flatten()
a1

array([0.98113162, 0.25215713, 0.95611457, 0.15409948, 0.40051184,
       0.32808972, 0.39998962, 0.83927836, 0.7268405 , 0.06647424,
       0.13775801, 0.09340984, 0.31842996, 0.66482999, 0.03565542,
       0.67810608])

In [29]:
a1.data

In [30]:
b = a.reshape(-1,16)
b

array([[0.98113162, 0.25215713, 0.95611457, 0.15409948, 0.40051184,
        0.32808972, 0.39998962, 0.83927836, 0.7268405 , 0.06647424,
        0.13775801, 0.09340984, 0.31842996, 0.66482999, 0.03565542,
        0.67810608]])

In [31]:
b.data

In [32]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [33]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [34]:
a.sum()

10

In [35]:
a.max(), a.min(), a.mean(), a.std()

(4, 0, 2.0, 1.4142135623730951)

In [36]:
# 평균(mean)
# 분산(Variance): 각원소와 평균의 차이의 제곱, 이들을 모두 합산, 그 값을 원소의 갯수로 나눔
# 표준편차(std) : 분산의 제곱근

In [79]:
a = np.random.random(16)
a

array([0.72278733, 0.82821895, 0.6831296 , 0.76333992, 0.91865439,
       0.85036498, 0.37858144, 0.83392073, 0.29303086, 0.18952472,
       0.53995875, 0.57728531, 0.90754187, 0.3173    , 0.65527255,
       0.8467376 ])

In [80]:
#평균
mean = a.mean()
mean

0.6441030629056325

In [84]:
#분산
variance = ((a - a.mean())**2).sum()/a.size
variance

0.05267967680175431

In [82]:
#표준편차
std = variance**(1/2)
std

8.33000234328132e-09

In [83]:
np.sqrt(np.mean((a-a.mean())**2)), np.std(a)

(0.2295205367755886, 0.2295205367755886)

In [85]:
a = np.arange(10,16)

In [86]:
a

array([10, 11, 12, 13, 14, 15])

In [87]:
a[2], a[-1], a[0], a[-6]

(12, 15, 10, 10)

In [88]:
a[a.size-1]

15

In [89]:
a[[1,2,3]]

array([11, 12, 13])

In [94]:
a = np.arange(1,17).reshape(4,-1)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [95]:
for e in a:
      print(e)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
[13 14 15 16]


In [96]:
for e in a:
      for i in e:
            print(i, end=' ')

1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 

In [97]:
a[1][2], a[1,2], a[[1,2]]

(7,
 7,
 array([[ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]))

In [108]:
a[3,1]

14

In [110]:
a[3,2:4]

array([15, 16])

In [115]:
#Fancy indexing : 인덱서 안에 정수나 불리언 배열을 사용하여 배열의 값을 추출하는 방법
ba = np.array([True,False,True,False,False,True,False,False,True,False,False,True,False,True,False,True])
ba = ba.reshape(4,-1)
ba

array([[ True, False,  True, False],
       [False,  True, False, False],
       [ True, False, False,  True],
       [False,  True, False,  True]])

In [116]:
a[ba]

array([ 1,  3,  6,  9, 12, 14, 16])

In [117]:
a<2

array([[ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [118]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [119]:
a[1:2]

array([[5, 6, 7, 8]])

In [120]:
A = np.arange(10, 19).reshape(3,-1)
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [122]:
A[0,:]

array([10, 11, 12])

In [139]:
A[[0,2],1:3]

array([[11, 12],
       [17, 18]])

In [140]:
for n  in A.flatten():
      print(n, end =" ")

10 11 12 13 14 15 16 17 18 

In [141]:
for n in A.ravel():
      print(n, end=' ')

10 11 12 13 14 15 16 17 18 

In [142]:
np.apply_along_axis(np.sum, axis=0, arr=A)

array([39, 42, 45])

In [144]:
ndarry = np.arange(1,17).reshape(4, -1)
ndarry

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [149]:
#axis=0 세로축, axis=1 가로축
np.apply_along_axis(np.max, axis=1, arr=ndarry)

array([ 4,  8, 12, 16])

In [154]:
#홀수 합 더하기
A[A%2==1].sum()

56

In [155]:
A.data

In [156]:
A1 = A.reshape(1, -1)
A1

array([[10, 11, 12, 13, 14, 15, 16, 17, 18]])

In [157]:
A1.data

In [159]:
A1.shape=(9,)
A1

array([10, 11, 12, 13, 14, 15, 16, 17, 18])

In [160]:
A1.shape = (3,-1)
A1

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [161]:
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [162]:
A.transpose()

array([[10, 13, 16],
       [11, 14, 17],
       [12, 15, 18]])

In [163]:
A = np.ones((3,3))
B = np.zeros((3,3))

In [164]:
np.vstack([A,B])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [165]:
np.hstack([A,B])

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [167]:
np.column_stack([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [168]:
np.row_stack([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [170]:
A = np.arange(16).reshape(4,-1)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [173]:
#수평분리
np.hsplit(A,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [175]:
#수직분리
np.vsplit(A,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [181]:
np.split(A, [2,3], axis=0)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

In [180]:
np.split(A, [1,3], axis=1)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

# Views, Copies

In [182]:
a= np.arange(1,5)
a

array([1, 2, 3, 4])

In [184]:
a

array([1, 2, 3, 4])

In [188]:
b = a.copy()

In [189]:
b

array([1, 2, 3, 4])

In [192]:
b[0] = 5

In [193]:
b

array([5, 2, 3, 4])

In [194]:
a

array([1, 2, 3, 4])

In [195]:
v2 = np.array([1,2]) * np.array([3,4])
v2

array([3, 8])

In [196]:
a*2

array([2, 4, 6, 8])

In [197]:
a*[2,2,2,2]

array([2, 4, 6, 8])

In [198]:
np.save('saved_ndarray', a)
print('파일 저장 성공')

파일 저장 성공


In [200]:
fa = np.load('saved_ndarray.npy')
fa

array([1, 2, 3, 4])