In [1]:
import numpy as np

In [8]:
# ndarry(다차원 배열) 
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [9]:
type(a)
# 한가지 자료형만 들어갈 수 있다.
a.dtype.name

'int32'

In [7]:
nums = ['a', 2, 'b', 'c', True, 3.14]
nums

['a', 2, 'b', 'c', True, 3.14]

In [12]:
#자료형이 하나로(문자열) 바뀜
b = np.array(nums)
b

array(['a', '2', 'b', 'c', 'True', '3.14'], dtype='<U32')

In [16]:
a = np.array([1,2,3,4,5])
#원소갯수
a.size
#차원
a.ndim
#헹,열
a.shape

(5,)

In [21]:
a = np.array([
            [1,2,3],
            [4,5,6]
            ])
a.size
a.ndim
a.shape
a.itemsize
a.data

In [24]:
a = np.array((
            [1,2,3],
            (4,5,6)
            ))
a

array([[1, 2, 3],
       [4, 5, 6]])

In [25]:
bool_array = np.array([True, False, False])
bool_array

array([ True, False, False])

In [27]:
float_array = np.array([1.2, 3.4, 5.6])
float_array
float_array.dtype.name

'float64'

In [31]:
complex_array = np.array([1+2j, 3+4j, 5+2j], dtype=complex)
complex_array
complex_array.dtype.name

'complex128'

In [32]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# 함수형 프로그래밍 (Functional Programming)
* map(): 컬랙션 원소에 대해 특정 계산을 적용함
* filter(): 컬렉션 원소에 대해 특정 원소만 필터링하여 새 집합 생성
* reduce(): 컬렉션 원소에 대해 계산을 수행하여 한개의 스칼라 값을 생성
* lamda(): 위의 함수에서 사용하는 첫번째 아규먼트인 함수(익명함수)

In [44]:
nums = [1,2,3,4,5]

def add(x): return x+1
list(map(add, nums))

[2, 3, 4, 5, 6]

In [49]:
def odd(x): return x%2==1
list(filter(odd, nums))

[1, 3, 5]

In [46]:
from functools import reduce

def sub(x, y): return x+y
reduce(sub, nums)

15

In [52]:
list(map(lambda x : x+1, nums))

[2, 3, 4, 5, 6]

In [53]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [65]:
import random

dataframe = np.zeros([2,3])

for i in range(2):
      for j in range(3):
            dataframe[i,j] = random.randint(1,9)
dataframe

array([[9., 9., 4.],
       [8., 2., 9.]])